name: Terraform Playground
on:
  push:
    branches:
      - main

jobs:
  Vars-Verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        AMBIENTE: ["des","prd"]
    environment: ${{ matrix.AMBIENTE }}
    steps:
      - name: Verify Variables
        run: |
          echo "Verifying variables for environment: $AMBIENTE"